import type { Metadata } from "next";
import "./globals.css";
import SideBar from "@/components/Sidebar/SideBar";
import { FilialContextProvider } from "@/providers/filial.provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className="w-[calc(100vw-40px)] h-[calc(100vh-40px)]">
        <main className={`flex flex-row gap-6 p-5 w-full h-full`}>
          <FilialContextProvider>
            <SideBar />
            <div className="w-full h-full">{children}</div>
          </FilialContextProvider>
        </main>
      </body>
    </html>
  );
}
